apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.main.name }}
  labels: 
    group: {{ .Values.main.group }}
spec:
  type: {{ .Values.main.service.type }}
  selector:             
    app: {{ .Values.main.name }}
  ports:
    - port: {{ .Values.main.service.port }}       
      targetPort: {{ .Values.main.container.port }}